version: '3.3'

services:
  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
    networks:
      - frontend
    command: ["npm", "run", "server"]

networks:
  frontend:
    enable_ipv6: false
    driver: bridge
